### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by brettle** [emmerge/meteor-google-fake#3]
What is the license associated with this project? I'd like to contribute a fix to @ryepdx's [meteor-linkedin-fake](https://github.com/ryepdx/meteor-linkedin-fake) but need to know the license first. That means I need to know the license for his package, your package (from which his is forked), and @xolvio's [meteor-github-stub package](https://github.com/xolvio/meteor-github-stub) from which your package is forked. I'm hoping all 3 of you will see this issue and add license files to your packages. Thanks!

Side note: @ryepdx, I'd have created this issue on your package, but you seem to have disabled issue creation and it wasn't clear how to otherwise report issues.

**Comment by SamHatoum** [comment]
Our's is now done:

https://github.com/xolvio/meteor-github-stub/blob/master/LICENSE

**Comment by wheeler** [comment]
Added a license to our project.

https://github.com/emmerge/meteor-google-fake/blob/master/LICENSE

**Comment by ghost** [comment]
Apologies. Didn't realize issue creation was disabled. I'll fix the issue
when I'm back at my computer.

**Comment by brettle** [comment]
Thanks to all 3 of you for the prompt action!
